### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by agreco** [braver/theme-sea-lion#5]
Hey,

Just recently received an update from package control and the icons are missing from the sidebar, and folder names are not bold anymore, is this expected?

Cheers

**Comment by braver** [comment]
Yeah, I probably should have communicated that. I need to figure out how to send messages about updates.... Sorry!

- I decided to lean on [A File Icon](https://packagecontrol.io/packages/A%20File%20Icon) for the icons. You can find out how to match the greyscale in my readme (or just go with the colors of course). It's a pretty powerful package and I felt they were providing the better implementation.
- I switched to the San Francisco font (if you're on a Mac), to match macOS, but it looks pretty bad in bold. 

I think it's pretty awesome you're using my theme, so if there's anything you need changed or that's suboptimal for you, please let me know!

**Comment by agreco** [comment]
Of course! Thanks for letting me know about the update of the icon package, much appreciated.
